---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBnlqW5eImiat9WzNEdvKCHmVUy7Fzi/CoxSLN2WiZl0Qo0NECJ3k9Vy3EFW8VKv/cdyzGO8A0TALm7D40WToAlN2vjKzISQSG06WGPaHDcej/iX47kuS/oI5pHpELRHLRcBzI6hYw0yTG764tLdTyDK/fJ4MUem3BcM1D4hxGUZQy3WK5D1JlsidiK4CYzejZpfX3YYlZiJWqQoddL0PewhWjNJ+BNF2DUDRTyvX+I3VzNvkPBDco+vWStCAhrijtcUs6g29Bo+k4jQtqm+S5DiYLweZ2818vkJHIfd3YhqTU9TIYb6diP413C2rKdQPd6iEZUfKPSIMKPZQVSAP/6h8Vw1ffF3fHcRJqvc+U30rU4hpL9NnEpIHfU9phASt0CI5JGeplcmcHE5K+op2zTfFQ2rybkhA3z/oZZRuJjoiItNWN9RWoht0e1JKolPOLVzaGwrNNH7P18OES2NPt18KLwmY9aynn4MHf3rjIEbwbnsSvl++nIkm+5bRSp7g73BYYLB30T7M3CsGlu32Najcgjbz+OUzCnf9U/Ri+p2MeGwXAXhacKoViNEP2RydgorfnrSrMm36bsMJz9aQIJU0Z/MY9UtgYNxAotFwaO1AdkOpu8lzuLt2TJRuzX2aklPuDT92mfgU1NItcxxHyWlJxh7JzDoRZHmwdxsXd1ch2i+5ITIr/+adzbAUyUEsxFmSQ3elLMRFzWEiLc2NrPmaXwGl+Ojlc=
    admin-user: AgBsqba7vi9CT9LvI9YRBKgAmzFWa55JYONy6+Iw7EQS0qndsHFy+1B8TB/cwu/HdRWaaTfgHZvfFp7ftYxjHP/i35HmV0vfPC6XVWHjp1kZG9feYj5vPU+yyNt/EAc6JJWOvTrw5t+aBpEdC4zl10KoEalW8/GnV80XbGXMnKy7+TQCMmphiOCnm7MaWLe4TkWV9P0akC+yAUWWS7RKZMcHSMj3ZEqcVea95/ruC4m5m7uaQEVmSH+6bzmSRJPuHmm/qKLD46YcGW4J6nQNofau/CBhlE15Y2H9p7qZbzTaPLuS3H57TAP91nrysHUXbJXQwbvyXwVhCso2AfBkP5zhID71QNJqPpe7nYhfOpIJEY8u3eoGXh3iuMzVg1oXtVhNBgHunj1NRjn2pAVaStcFp45UH/ApDtU3pUxq0wix5bIsJfNshXu7LpvWE9xyncwqSUmK0ekZ24llJuyLsGaH6DnY8TYuSykcj+AzFfVTx649CKIOFm1phKMeZBSkrs9AGJNGh9W7ufPmaQzsCQkeFPS9AX1Fd2mRWJHaCtxT+0O3Y8FUrsPKfhEheC5bJZ5OGjS4H5fzIZYXqoG4bREM7GiWAYqtl2sqZ4MSgseU+okoAmiUf7nuMhGg+9/2/7qTWjhixNMhCxemwpDTSUZ6YZYBnNbXl52MVa57S+q7CluD4ixW0u5iH5zw6195FX2nrbKiJA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-smtp-secret
  namespace: monitoring
spec:
  encryptedData:
    smtp-password: AgAWSTtCGGZM0VAW7w7veyysRUlkASerPNphUgnCUN2wmCkQSb9PlsjLGAF6yfdu3djfjYyB7kIkdAu7jMzNhcai6rfRU7siBVY/zlpTbDuckOia/tN4f98rFj6EB2r1pAFI6PoeipP/hapxbDbQYRpqGIcHe2X5KucjXKfR8DrWD/r9rGta6zdcmJMUi6BwmBBmqAliiopKS7tNzS3ZHCauM+m9yU+oJaepwl+g3jLfGmoOipEH7Fc4QugcuWGVfnTrZf25sgggERf7qUYQDZ43eQZLTddyaeYjNYrG0JgebEJqLFNmcUQoPldKPC5c+6RnLNEQAb+zyEmpwmtJlVGuBS4nfNpeepQG4UMGi9KOZy1QrSIUE0lxsnGmkooPfrIl1iOUndAmlF2GXanjXNpr2RmB/0l35qdkPPKlIJ51blWO/le7ZrNk25vvNoFeoSfwhQ4FCkdRTGZtG1Tq9Hp1Ieykbxlpq4VcANvDLeyKX5p8gS1EbVgC81l8nWhwspj2xWYyS09U7e7QlYwzwRH4GoIiTub2LugqiC7xQ3eqVIrFSzVxF+kMH4Dm1ieYgpHU6wNXMYAl9z66C4JZRjbDYsOFzCoCKQProdc0XhdGRoGMSJDD39OzCCct/rmDwgzgYPSe6bf/5Jd+Gp7G/DqqbLsWmNCDLd7gtQszBKeaipCceVMHJQsM2AeyyOArKzUYvharbT2/JD5NVBV192Rsw2uo
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-smtp-secret
      namespace: monitoring
    type: Opaque
