"use client";
/* eslint-disable react-hooks/incompatible-library */
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query"; import { flexRender, getCoreRowModel, useReactTable, type ColumnDef } from "@tanstack/react-table";
import { Activity, Gavel, GraduationCap, MoreHorizontal, Search, ShieldCheck, UserRound, Users } from "lucide-react"; import { enqueueSnackbar } from "notistack";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Sheet, SheetContent, SheetDescription, SheetTitle } from "@/components/ui/sheet";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ManagementPageHeader } from "@/components/organizer/shared/management-page-header"; import { ManagementMetricGrid } from "@/components/organizer/shared/management-metric-grid"; import { ManagementEmpty, ManagementError, ManagementSkeleton } from "@/components/organizer/shared/management-states";
import type { OrganizerPerson, PeopleFilters } from "@/lib/organizer/management-types"; import { organizerManagementService } from "@/services/organizer-management.service";

const roleVariant = { Student: "default", Stakeholder: "outline", Mentor: "success", Judge: "ai", Organizer: "warning" } as const;
const statusVariant = { Active: "success", Inactive: "outline", Removed: "destructive", Disqualified: "destructive" } as const;
export function PeopleClient() {
  const [filters, setFilters] = useState<PeopleFilters>({ search: "", role: "All", status: "All", page: 1, limit: 10 });
  const [selected, setSelected] = useState<OrganizerPerson | null>(null); const [drawerOpen, setDrawerOpen] = useState(false); const [assignOpen, setAssignOpen] = useState(false);
  const query = useQuery({ queryKey: ["organizer-people", filters], queryFn: () => organizerManagementService.getPeople(filters) });
  const summaryQuery = useQuery({ queryKey: ["organizer-people-summary"], queryFn: () => organizerManagementService.getPeopleSummary() });
  const columns = useMemo<ColumnDef<OrganizerPerson>[]>(() => [
    { accessorKey: "name", header: "Person", cell: ({ row }) => <div className="flex min-w-56 items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-orange-500/10 text-xs font-semibold text-orange-400">{row.original.name.split(" ").map((word) => word[0]).slice(0, 2).join("")}</span><div><p className="font-medium">{row.original.name}</p><p className="text-xs text-muted-foreground">{row.original.email}</p><p className="text-[10px] text-muted-foreground">{row.original.code}</p></div></div> },
    { accessorKey: "role", header: "Role", cell: ({ row }) => <Badge variant={roleVariant[row.original.role]}>{row.original.role}</Badge> },
    { accessorKey: "event", header: "Event" }, { accessorKey: "assignment", header: "Team / Assignment" },
    { accessorKey: "participationStatus", header: "Participation", cell: ({ row }) => <Badge variant={statusVariant[row.original.participationStatus]}>{row.original.participationStatus}</Badge> },
    { accessorKey: "lastActive", header: "Last Active" },
    { id: "actions", header: "Actions", cell: ({ row }) => <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`Actions for ${row.original.name}`}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => { setSelected(row.original); setDrawerOpen(true); }}>View Profile</DropdownMenuItem>{(row.original.role === "Mentor" || row.original.role === "Judge") && <DropdownMenuItem onClick={() => { setSelected(row.original); setAssignOpen(true); }}>Assign {row.original.role}</DropdownMenuItem>}<DropdownMenuItem onClick={() => enqueueSnackbar(`Notification prepared for ${row.original.name}`, { variant: "info" })}>Send Notification</DropdownMenuItem><DropdownMenuItem className="text-red-400">Remove From Event</DropdownMenuItem></DropdownMenuContent></DropdownMenu> },
  ], []);
  const table = useReactTable({ data: query.data?.data ?? [], columns, getCoreRowModel: getCoreRowModel() });
  const summary = summaryQuery.data; const metrics = [{ label: "Total People", value: summary?.total ?? 0, detail: "All database users", icon: Users }, { label: "Students", value: summary?.students ?? 0, detail: "All student accounts", icon: GraduationCap }, { label: "Stakeholders", value: summary?.stakeholders ?? 0, detail: "Not assigned to an event role", icon: UserRound }, { label: "Mentors", value: summary?.mentors ?? 0, detail: "Current event assignments", icon: UserRound }, { label: "Judges", value: summary?.judges ?? 0, detail: "Current event assignments", icon: Gavel }, { label: "Organizers", value: summary?.organizers ?? 0, detail: "Organizer and admin accounts", icon: ShieldCheck }, { label: "Active People", value: summary?.active ?? 0, detail: "Active participation status", icon: Activity }];
  return <div className="space-y-6"><ManagementPageHeader eyebrow="Event community" title="People" description="Manage people participating in your assigned events without changing global accounts." actions={<Button variant="outline">Export People</Button>} /><ManagementMetricGrid metrics={metrics} />
    <div className="flex flex-col gap-3 rounded-2xl border border-border bg-card/60 p-4 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value, page: 1 })} placeholder="Search name or email..." className="pl-9" /></div>{["role", "status"].map((field) => <Select key={field} value={filters[field as "role" | "status"]} onValueChange={(value) => value && setFilters({ ...filters, [field]: value, page: 1 })}><SelectTrigger className="w-full md:w-44"><SelectValue /></SelectTrigger><SelectContent>{(field === "role" ? ["All", "Student", "Stakeholder", "Mentor", "Judge", "Organizer"] : ["All", "Active", "Inactive", "Removed", "Disqualified"]).map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select>)}</div>
    {query.isError ? <ManagementError onRetry={() => void query.refetch()} /> : query.isLoading ? <ManagementSkeleton /> : !query.data?.data.length ? <ManagementEmpty label="people" /> : <div className="overflow-hidden rounded-2xl border border-border"><Table><TableHeader>{table.getHeaderGroups().map((group) => <TableRow key={group.id}>{group.headers.map((header) => <TableHead key={header.id}>{flexRender(header.column.columnDef.header, header.getContext())}</TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.map((row) => <TableRow key={row.id}>{row.getVisibleCells().map((cell) => <TableCell key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</TableCell>)}</TableRow>)}</TableBody></Table><div className="flex items-center justify-between border-t p-3 text-sm text-muted-foreground"><span>{query.data.pagination.total} people</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={filters.page === 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>Previous</Button><Button variant="outline" size="sm" disabled={filters.page >= query.data.pagination.totalPages} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>Next</Button></div></div></div>}
    <Sheet open={drawerOpen} onOpenChange={setDrawerOpen}><SheetContent side="right" className="w-full overflow-y-auto p-5 sm:max-w-xl"><SheetTitle>{selected?.name}</SheetTitle><SheetDescription>{selected?.email} · {selected?.role}</SheetDescription>{selected && <Tabs defaultValue="profile" className="mt-6"><TabsList><TabsTrigger value="profile">Profile</TabsTrigger><TabsTrigger value="events">Events</TabsTrigger><TabsTrigger value="assignment">Assignment</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList><TabsContent value="profile" className="mt-5 space-y-3"><p><span className="text-muted-foreground">Department:</span> {selected.department}</p><p><span className="text-muted-foreground">Skills:</span> {selected.skills.join(", ")}</p><p>{selected.bio}</p></TabsContent><TabsContent value="events" className="mt-5 rounded-xl border p-4">{selected.event} · {selected.participationStatus}</TabsContent><TabsContent value="assignment" className="mt-5 rounded-xl border p-4">{selected.assignment}</TabsContent><TabsContent value="activity" className="mt-5 rounded-xl border p-4">Last active {selected.lastActive}</TabsContent></Tabs>}</SheetContent></Sheet>
    <Dialog open={assignOpen} onOpenChange={setAssignOpen}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Assign {selected?.role}</DialogTitle><DialogDescription>Assignment is limited to events you manage.</DialogDescription></DialogHeader><div className="space-y-3"><Select defaultValue={selected?.event}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value={selected?.event ?? "event"}>{selected?.event}</SelectItem></SelectContent></Select><Input placeholder={selected?.role === "Judge" ? "Round / track" : "Team"} /><Input placeholder="Assignment note" /></div><DialogFooter><Button variant="outline" onClick={() => setAssignOpen(false)}>Cancel</Button><Button onClick={() => { enqueueSnackbar(`${selected?.role} assigned successfully`, { variant: "success" }); setAssignOpen(false); }}>Confirm Assignment</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
