---
- name: Check if Helm is installed
  stat:
    path: /usr/local/bin/helm
  register: helm_binary

- name: Install Helm Package Manager
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when: not helm_binary.stat.exists

- name: Ensure Traefik Ingress Controller is active on K3s Control Plane
  command: kubectl get svc -n kube-system traefik
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
