apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hackathon-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SEAL-WDP301/SEAL-WDP301-monorepo.git
    targetRevision: production
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: hackathon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
