"use client";
/* eslint-disable react-hooks/incompatible-library */
import { useEffect } from "react"; import { useForm } from "react-hook-form"; import { useMutation, useQuery } from "@tanstack/react-query"; import { enqueueSnackbar } from "notistack";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"; import { Badge } from "@/components/ui/badge";
import { ManagementPageHeader } from "@/components/organizer/shared/management-page-header"; import { ManagementSkeleton } from "@/components/organizer/shared/management-states"; import type { OrganizerSettings } from "@/lib/organizer/management-types"; import { organizerManagementService } from "@/services/organizer-management.service";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1.5 text-sm font-medium">{label}{children}</label>; }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="flex items-center justify-between gap-4 rounded-xl border border-border p-3"><span><span className="block text-sm font-medium">{label}</span><span className="text-xs text-muted-foreground">{description}</span></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="size-4 accent-orange-500" /></label>; }
export function SettingsClient() {
  const query = useQuery({ queryKey: ["organizer-settings"], queryFn: () => organizerManagementService.getSettings() }); const form = useForm<OrganizerSettings>();
  useEffect(() => { if (query.data) form.reset(query.data); }, [form, query.data]);
  const mutation = useMutation({ mutationFn: (settings: OrganizerSettings) => organizerManagementService.saveSettings(settings), onSuccess: () => enqueueSnackbar("Settings saved", { variant: "success" }), onError: () => enqueueSnackbar("Unable to save settings", { variant: "error" }) });
  if (query.isLoading || !query.data) return <ManagementSkeleton />; const settings = form.watch();
  return <div className="space-y-6"><ManagementPageHeader eyebrow="Personal workspace" title="Settings" description="Manage your organizer profile, event defaults, notification preferences and security." actions={<Button onClick={form.handleSubmit((data) => mutation.mutate(data))} disabled={mutation.isPending}>{mutation.isPending ? "Saving..." : "Save Changes"}</Button>} />
    <Tabs defaultValue="profile"><TabsList className="max-w-full overflow-x-auto"><TabsTrigger value="profile">Profile</TabsTrigger><TabsTrigger value="defaults">Event Defaults</TabsTrigger><TabsTrigger value="notifications">Notifications</TabsTrigger><TabsTrigger value="preferences">Preferences</TabsTrigger><TabsTrigger value="security">Security</TabsTrigger></TabsList>
      <TabsContent value="profile" className="mt-6"><div className="grid max-w-3xl gap-4 rounded-2xl border border-border bg-card/60 p-5 sm:grid-cols-2"><Field label="Full name"><Input {...form.register("profile.fullName")} /></Field><Field label="Email"><Input {...form.register("profile.email")} readOnly /></Field><Field label="Phone"><Input {...form.register("profile.phone")} /></Field><Field label="Department"><Input {...form.register("profile.department")} /></Field><Field label="Position"><Input {...form.register("profile.position")} /></Field><Field label="Bio"><Textarea {...form.register("profile.bio")} className="min-h-24" /></Field></div></TabsContent>
      <TabsContent value="defaults" className="mt-6"><div className="grid max-w-4xl gap-4 rounded-2xl border border-border bg-card/60 p-5 sm:grid-cols-2"><Field label="Default season"><Select value={settings.eventDefaults.season} onValueChange={(value) => value && form.setValue("eventDefaults.season", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{["Spring", "Summer", "Fall"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></Field><Field label="Registration mode"><Input {...form.register("eventDefaults.registrationMode")} /></Field><Field label="Minimum team size"><Input type="number" {...form.register("eventDefaults.minTeamSize", { valueAsNumber: true })} /></Field><Field label="Maximum team size"><Input type="number" {...form.register("eventDefaults.maxTeamSize", { valueAsNumber: true })} /></Field><Field label="Submission file limit (MB)"><Input type="number" {...form.register("eventDefaults.fileLimit", { valueAsNumber: true })} /></Field><Field label="Time zone"><Input {...form.register("eventDefaults.timezone")} /></Field><Field label="Event visibility"><Input {...form.register("eventDefaults.visibility")} /></Field><Field label="Date format"><Input {...form.register("eventDefaults.dateFormat")} /></Field></div></TabsContent>
      <TabsContent value="notifications" className="mt-6"><div className="grid max-w-4xl gap-3 sm:grid-cols-2">{Object.entries(settings.notifications).map(([key, value]) => <Toggle key={key} label={key.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase())} description="Receive this notification for assigned events." checked={value} onChange={(checked) => form.setValue(`notifications.${key}`, checked)} />)}</div></TabsContent>
      <TabsContent value="preferences" className="mt-6"><div className="grid max-w-4xl gap-4 rounded-2xl border border-border bg-card/60 p-5 sm:grid-cols-2"><Field label="Theme"><Input {...form.register("preferences.theme")} /></Field><Field label="Language"><Input {...form.register("preferences.language")} /></Field><Field label="Time zone"><Input {...form.register("preferences.timezone")} /></Field><Field label="Date format"><Input {...form.register("preferences.dateFormat")} /></Field><Field label="Default dashboard event"><Input {...form.register("preferences.defaultEvent")} /></Field><Field label="Default table page size"><Input type="number" {...form.register("preferences.pageSize", { valueAsNumber: true })} /></Field><Toggle label="Reduced motion" description="Reduce animations throughout the organizer workspace." checked={settings.preferences.reducedMotion} onChange={(checked) => form.setValue("preferences.reducedMotion", checked)} /></div></TabsContent>
      <TabsContent value="security" className="mt-6 space-y-5"><div className="max-w-2xl rounded-2xl border border-border bg-card/60 p-5"><h2 className="font-semibold">Change password</h2><div className="mt-4 grid gap-3"><Input type="password" placeholder="Current password" /><Input type="password" placeholder="New password" /><Button className="w-fit" onClick={() => enqueueSnackbar("Password update request submitted", { variant: "success" })}>Change Password</Button></div></div><div className="max-w-3xl rounded-2xl border border-border bg-card/60 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Active sessions</h2><Button variant="destructive" size="sm">Logout Other Sessions</Button></div><div className="mt-4 divide-y divide-border">{settings.sessions.map((session) => <div key={session.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-medium">{session.device} {session.current && <Badge variant="success" className="ml-2">Current</Badge>}</p><p className="text-xs text-muted-foreground">{session.location} · {session.lastActive}</p></div>{!session.current && <Button variant="outline" size="sm">Revoke</Button>}</div>)}</div></div></TabsContent>
    </Tabs></div>;
}
